---
development: &defaults
  adapter: mysql
  database: weblog_development
  username: root
  password: 
  socket: /tmp/mysql.sock
  host: localhost
  encoding: utf8

test:
  <<: *defaults
  database: weblog_test

production:
  <<: *defaults
  database: weblog_production
 
rake:
  <<: *defaults